//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\axelg\QueryDesign\sql.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="sqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IsqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.sql"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql([NotNull] sqlParser.SqlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.tabla"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTabla([NotNull] sqlParser.TablaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.innerkw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInnerkw([NotNull] sqlParser.InnerkwContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.leftkw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftkw([NotNull] sqlParser.LeftkwContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.rightkw"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRightkw([NotNull] sqlParser.RightkwContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.columna"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumna([NotNull] sqlParser.ColumnaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.campo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCampo([NotNull] sqlParser.CampoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="sqlParser.columna_p"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumna_p([NotNull] sqlParser.Columna_pContext context);
}
